{% set name = "nutpie" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nutpie-{{ version }}.tar.gz
  sha256: 7ffaa5aeb1947fa12928dd34d50c2d12ded263ae5e21e3a26a3b5fcdf3050503

build:
  number: 0
  skip: true  # [py<310]
  ignore_run_exports_from:
    - libclang

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.1,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - libclang
    - clang
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - pip
    - numpy
    - maturin >=1.1,<2.0
  run:
    - python
    - pyarrow-core >=12.0.0
    - pandas >=2.0
    - xarray >=2023.06.0
    - arviz >=0.15.0
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - pymc-base >=5.5.0
    - pytensor-base >=2.8.11
    - numba >=0.57

test:
  imports:
    - nutpie
  requires:
    - pip
    - pytest
    - pymc-base
    - numba
    - jax  # [not win]
  commands:
    - pip check
    - pytest tests/test_pymc.py  # [not win]
    - pytest tests/test_pymc.py -k "not jax"  # [win]
  source_files:
    - tests

about:
  home: https://github.com/pymc-devs/nutpie
  summary: Sample Stan or PyMC models
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - twiecki
    - aseyboldt
    - maresb
    - lucianopaz
    - ferrine
