{% set name = "nutpie" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/nutpie/archive/v{{ version }}.tar.gz
  sha256: e5ef8ac41824f443cce317df3182f02efbf2d5389044d6b4dab3f986a099ac37

build:
  number: 0
  skip: true  # [py<39]
  ignore_run_exports_from:
    - libclang

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.1,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - libclang
    - clang
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - pip
    - numpy
    - maturin >=1.1,<2.0
  run:
    - python
    - pymc-base >=5.5.0
    - arviz
    - xarray
    - pytensor >=2.8.11
    - numba >=0.57
    - fastprogress
    - pyarrow
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nutpie
  requires:
    - pytest
  commands:
    - pytest tests/test_pymc.py
  source_files:
    - tests

about:
  home: https://github.com/pymc-devs/nutpie
  summary: A fast and simple sampler for bayesian posterior distributions
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - aseyboldt
