{% set name = "nutpie" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aseyboldt/nutpie/archive/v{{ version }}.tar.gz
  sha256: c4ce8d208e4739730f87000209443feca074971582915116fb6a997b835106f9

build:
  number: 0
  skip: true  # [py<38]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - maturin build --bindings pyo3 --no-sdist --release --interpreter {{ PYTHON }} --out wheels
    - {{ PYTHON }} -m pip install -vv --no-build-isolation --no-deps --no-index --find-links ./wheels nutpie

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - pip
    - maturin
  run:
    - python
    - pymc-base
    - arviz
    - aesara
    - aeppl
    - numba
    - fastprogress

test:
  imports:
    - nutpie
  requires:
    - pytest
  commands:
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/aseyboldt/nutpie
  summary: A fast and simple sampler for bayesian posterior distributions
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - aseyboldt
