{% set name = "nutpie" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aseyboldt/nutpie/archive/v{{ version }}.tar.gz
  sha256: cdd75ec01d0d73313d83054bd420f626be189a0a63082a200e07ca25133fa43e

build:
  number: 0
  skip: true  # [py<38]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - maturin build --bindings pyo3 --release --interpreter {{ PYTHON }} --out wheels
    - {{ PYTHON }} -m pip install -vv --no-build-isolation --no-deps --no-index --find-links ./wheels nutpie

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=0.13
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pymc-base
    - arviz
    - aesara >=2.8.2
    - numba >=0.55
    - fastprogress

test:
  imports:
    - nutpie
  requires:
    - pytest
  commands:
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/aseyboldt/nutpie
  summary: A fast and simple sampler for bayesian posterior distributions
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - aseyboldt
