{% set name = "nutpie" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/nutpie/archive/v{{ version }}.tar.gz
  sha256: b1e11eca719903499e17990b67007099d958cdac607fd60d0533b14b03250db0

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.13,<0.14                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - pip
    - numpy
    - maturin >=0.13,<0.14
  run:
    - python
    - pymc-base
    - arviz
    - xarray
    - aesara >=2.8.2
    - numba >=0.56
    - fastprogress
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nutpie
  requires:
    - pytest
  commands:
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/pymc-devs/nutpie
  summary: A fast and simple sampler for bayesian posterior distributions
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - aseyboldt
