schema_version: 1

context:
  name: nutpie
  version: 0.16.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nutpie-${{ version }}.tar.gz
  sha256: 2be8c0c55e6823244d08ad4eb3eb52a5538091734f6f61dc5f8f1aa534df845b

build:
  number: 2
  skip: match(python, "<3.11") or ppc64le

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: maturin >=1.1,<2.0
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - libclang
    - clang
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - pip
    - numpy >=1.25.0
    - maturin >=1.1,<2.0
  run:
    - python
    - pyarrow-core >=12.0.0
    - pandas >=2.0
    - xarray >=2025.01.2
    - arviz >=0.20.0
    - arro3-core >=0.6.0
    - zarr >=3.1.0
    - obstore >=0.8.0
  ignore_run_exports:
    from_package:
      - libclang
  run_constraints:
    - pymc-base >=5.20.1
    - numba >=0.60

tests:
  - python:
      imports:
        - nutpie
  - files:
      source:
        - tests
    requirements:
      run:
        - pip
        - pytest
        - pymc-base >=5.24
        - numba >=0.62
    script:
      - pip check
      - pytest tests/test_pymc.py -k "not jax and not test_wait_timeout and not test_pause" -m "not flow" -vv

about:
  summary: Sample Stan or PyMC models
  description: |
    nutpie implements NUTS, an advanced gradient based sampler
    for posterior distributions, with an easy to use interface.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/pymc-devs/nutpie

extra:
  recipe-maintainers:
    - twiecki
    - aseyboldt
    - maresb
    - lucianopaz
    - ferrine
